<a href="https://colab.research.google.com/github/HasankaRajakaruna/APAN56-Datathon/blob/main/churn_sorter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

In [ ]:
upload = files.upload()

Saving filtered_source_data.csv to filtered_source_data.csv

In [ ]:
train_churn_list = pd.read_csv('/content/filtered_source_data.csv')
train_churn_list.head()

,customer_id,day_no,usage_app_facebook_daily,usage_app_helakuru_daily,usage_app_other,usage_app_tiktok_daily,usage_app_whatsapp_daily,usage_app_youtube_daily,usage_pack_data,usage_pack_vas,usage_voice_d2d_incoming,usage_voice_d2d_outgoing,usage_voice_d2nd_outgoing,usage_voice_nd2d_incoming
0,9e2adb8e95b6d4f0d645ad02c8cbd935ec7701ec5da225...,1,82.51,10.08,89.54,100.64,0.00,119.08,60.60,19.70,16.37,22.25,87.20,15.47
1,9e2adb8e95b6d4f0d645ad02c8cbd935ec7701ec5da225...,2,67.23,9.73,108.57,21.11,31.91,36.45,94.42,18.98,20.88,15.80,49.47,9.86
2,9e2adb8e95b6d4f0d645ad02c8cbd935ec7701ec5da225...,3,80.07,9.69,103.84,102.24,1.21,0.00,0.00,18.17,19.58,19.96,147.98,18.14
3,9e2adb8e95b6d4f0d645ad02c8cbd935ec7701ec5da225...,4,76.98,9.36,103.62,68.50,12.90,457.02,20.95,17.51,17.42,17.82,22.70,23.14
4,9e2adb8e95b6d4f0d645ad02c8cbd935ec7701ec5da225...,5,62.51,9.29,41.36,17.07,9.40,32.20,76.09,16.61,16.93,14.20,0.00,15.01

In [ ]:
sorted_train_churn_list = train_churn_list.sort_values(by=['customer_id', 'day_no'],ascending=True)

In [ ]:
sorted_train_churn_list.head(250)

,customer_id,day_no,usage_app_facebook_daily,usage_app_helakuru_daily,usage_app_other,usage_app_tiktok_daily,usage_app_whatsapp_daily,usage_app_youtube_daily,usage_pack_data,usage_pack_vas,usage_voice_d2d_incoming,usage_voice_d2d_outgoing,usage_voice_d2nd_outgoing,usage_voice_nd2d_incoming
0,9e2adb8e95b6d4f0d645ad02c8cbd935ec7701ec5da225...,1,82.51,10.08,89.54,100.64,0.00,119.08,60.60,19.70,16.37,22.25,87.20,15.47
1,9e2adb8e95b6d4f0d645ad02c8cbd935ec7701ec5da225...,2,67.23,9.73,108.57,21.11,31.91,36.45,94.42,18.98,20.88,15.80,49.47,9.86
2,9e2adb8e95b6d4f0d645ad02c8cbd935ec7701ec5da225...,3,80.07,9.69,103.84,102.24,1.21,0.00,0.00,18.17,19.58,19.96,147.98,18.14
3,9e2adb8e95b6d4f0d645ad02c8cbd935ec7701ec5da225...,4,76.98,9.36,103.62,68.50,12.90,457.02,20.95,17.51,17.42,17.82,22.70,23.14
4,9e2adb8e95b6d4f0d645ad02c8cbd935ec7701ec5da225...,5,62.51,9.29,41.36,17.07,9.40,32.20,76.09,16.61,16.93,14.20,0.00,15.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,f4972d45b42830d180360f2a2b5e921e5f67aa18ad09e9...,66,0.00,0.00,0.00,0.00,0.00,0.00,0.00,57.85,0.00,0.00,0.00,0.00
246,f4972d45b42830d180360f2a2b5e921e5f67aa18ad09e9...,67,0.00,0.00,146.14,0.00,0.00,0.00,64.60,0.00,0.00,0.00,0.00,168.14
247,f4972d45b42830d180360f2a2b5e921e5f67aa18ad09e9...,68,0.00,0.00,529.40,0.00,0.00,0.00,60.95,0.00,22.16,0.00,0.00,98.97
248,f4972d45b42830d180360f2a2b5e921e5f67aa18ad09e9...,69,0.00,0.00,0.00,0.00,0.00,0.00,64.11,0.00,0.00,0.00,0.00,255.38
249,f4972d45b42830d180360f2a2b5e921e5f67aa18ad09e9...,70,0.00,0.00,0.00,0.00,0.00,0.00,63.02,0.00,0.00,0.00,0.00,236.74

In [ ]:
sorted_train_churn_list.to_csv('sorted_filtered_source_data.csv', index=False)